MODULE INITIALISE
  USE interface_array
  IMPLICIT NONE
CONTAINS

  FUNCTION INIT(INI_ARRAY_AI, INI_ARRAY_TYPE) RESULT(INI_ARRAY_OUT)
    INTEGER :: OUTLOOPIDX, INLOOPIDX
    REAL, DIMENSION(:,:,:), INTENT(IN) :: INI_ARRAY_AI
    REAL, DIMENSION(:,:), INTENT(IN) :: INI_ARRAY_TYPE
    REAL, DIMENSION(&
      SIZE(INI_ARRAY_AI, 1),&
      SIZE(INI_ARRAY_AI, 2),&
      SIZE(INI_ARRAY_AI, 3)) :: INI_ARRAY_OUT

    DO OUTLOOPIDX = 1, SIZE(INI_ARRAY_AI, 1)
      DO INLOOPIDX = 1, SIZE(INI_ARRAY_AI, 2)
        INI_ARRAY_OUT(OUTLOOPIDX,INLOOPIDX,:) = &
          INTERFACE_FUNC(&
            INI_ARRAY_AI(OUTLOOPIDX,INLOOPIDX,:),&
            INI_ARRAY_TYPE(INLOOPIDX,:))
      END DO
    END DO
  END FUNCTION INIT

END MODULE INITIALISE
